@startuml
class Graph {
    + Graph(directed:bool, noEdgeValue:float)
    + Order : int <<get>>
    + Directed : bool <<get>>
    + AddVertex(name:string, value:float) : void
    + RemoveVertex(name:string) : void
    + GetVertexValue(name:string) : float
    + SetVertexValue(name:string, value:float) : void
    + GetNeighbors(vertexName:string) : List<string>
    + AddEdge(sourceName:string, destinationName:string, weight:float) : void
    + RemoveEdge(sourceName:string, destinationName:string) : void
    + GetEdgeWeight(sourceName:string, destinationName:string) : float
    + SetEdgeWeight(sourceName:string, destinationName:string, weight:float) : void
    + Création() : List<string>
}
@enduml
