@startuml
class Matrix {
    + Matrix(nbRows:int, nbColumns:int, defaultValue:float)
    + DefaultValue : float <<get>>
    + NbRows : int <<get>>
    + NbColumns : int <<get>>
    + AddRow(j:int) : void
    + AddColumn(j:int) : void
    + RemoveRow(i:int) : void
    + RemoveColumn(j:int) : void
    + GetValue(i:int, j:int) : float
    + SetValue(i:int, j:int, v:float) : void
    + Print() : void
}
@enduml
