@startuml
class MatrixTests {
    + EmpyMatrix() : void
    + Dimensions23() : void
    + NegativeDimensions() : void
    + DefaultValue() : void
    + GetValueInvalidIndex() : void
    + SetValueInvalidIndex() : void
    + SetValues32() : void
    + SetValues23() : void
    + AddRowInvalidIndex() : void
    + AddRowBeginning() : void
    + AddRowMiddle() : void
    + AddRowEnd() : void
    + RemoveRowInvalidIndex() : void
    + RemoveRow() : void
    + AddColumnInvalidIndex() : void
    + AddColumnBeginning() : void
    + AddColumnMiddle() : void
    + AddColumnEnd() : void
    + RemoveColumnInvalidIndex() : void
    + RemoveColumn() : void
}
@enduml
