@startuml
!include ./Objectif1/TourneeFutee.Tests/MatrixTests.puml
!include ./Objectif1/TourneeFutee.Tests/LittleTests.puml
!include ./Objectif1/TourneeFutee.Tests/GraphTests.puml
!include ./Objectif1/TourneeFutee/Graph.puml
!include ./Objectif1/TourneeFutee/Matrix.puml
!include ./Objectif1/TourneeFutee/Little.puml
!include ./Objectif1/TourneeFutee/ServicePersistanceAcompleter.puml
!include ./Objectif1/TourneeFutee/Tour.puml
!include ./Objectif1/TourneeFutee/Program.puml
!include ./obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./obj/Debug/net8.0/TourneeFutee.GlobalUsings.g.puml
!include ./obj/Debug/net8.0/TourneeFutee.AssemblyInfo.puml
!include ./Objectif1/TourneeFutee.Tests/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./Objectif1/TourneeFutee.Tests/obj/Debug/net8.0/TourneeFutee.Tests.AssemblyInfo.puml
!include ./Objectif1/TourneeFutee.Tests/obj/Debug/net8.0/TourneeFutee.Tests.GlobalUsings.g.puml
!include ./Objectif1/TourneeFutee/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./Objectif1/TourneeFutee/obj/Debug/net8.0/TourneeFutee.GlobalUsings.g.puml
!include ./Objectif1/TourneeFutee/obj/Debug/net8.0/TourneeFutee.AssemblyInfo.puml
@enduml
